Update README to include EKS
Kralizek/AWSSecretsManagerConfigurationExtensions pull request #69
Opened 2022-06-17 11:30 UTC by OliverRC

The IAM roles for Service Accounts feature was added to allow EKS pods to talk to AWS Secret Manager using a Service Account. This allows roles to be used natively in EKS.
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html

However, the library was using a very old version of the AWS SDK that did not support this.

I wasn't quite sure if I should go with the lowest version where this feature was added or the latest SDK. I am open to feedback and can alter the PR if necessary. 

It is kind of hard to backtrack to what exact version of `AWSSDK.SecretsManager` is the minimum version as they only list the minimum SDK version which is not on the same version numbers. https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html

I also tried to provide some guidance on the EKS side of things as an additional library is required.

2022-06-17 14:35 UTC, OliverRC commented
@Kralizek no I didn't, thank you so much. I'll modify the PR to just include the README for now then.

I do feel at some point it would make sense to do a release with a more recent SDK version so isn't required to go outside the dependency chain.

2022-06-17 14:37 UTC, Kralizek commented
@OliverRC I agree, but until there is no breaking change from AWS or in the API of this library, it's better this way.

2022-08-02 11:55 UTC, OliverRC commented
I have removed the changes to the SDK versions and just left the changes to the README.

2022-08-02 12:52 UTC, Kralizek requested changes

2022-08-02 12:52 UTC, Kralizek commented on README.md
> +    dotnet add AWSSDK.SecurityToken
Put this one in a code block.

2022-08-02 21:26 UTC, Kralizek approved these changes

2022-08-02 21:27 UTC, merged